kind: pipeline
type: docker
name: mysql-test
    
clone:
  depth: 1

steps:

- name: mysql test
  image: mysql
  commands:
  - sleep 60
  - mysql -u root -h database --execute="SELECT VERSION();"

services:
  - name: database
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test
