kind: pipeline
type: docker
name: localstack

trigger:
  branch:
  - main

- name: localstack
  image: localstack/localstack

steps:

- name: localstack-up
  image: alpine/curl:3.14
  commands:
  # Checks to see that localstack service is up and running
  - echo -n waiting for localstack && STACK=down && while [ "$STACK" == "down" ]; do echo -n "." && sleep 3 && curl -sm 1 localstack:4566/health >>/dev/null && STACK=up; done
  - curl localstack:4566/health

- name: curl
  image: alpine:3
  commands:
  - apk add bind-tools curl
  - host gitea-127.0.0.1.sslip.io
  - host drone
  - curl drone:80
