kind: pipeline
type: docker
name: localstack

trigger:
  branch:
  - main

steps:

- name: git
  image: alpine/git
  commands:
  - git clone http://gitea-http.gitea:3000/demo/drone-quickstart.git

- name: curl
  image: alpine:3
  commands:
  - apk add bind-tools curl
  - host gitea-127.0.0.1.sslip.io
  - host drone
  - curl drone:80

- name: cat-hosts
  image: alpine:3
  commands:
  - cat /etc/hosts
